# Generated by Django 5.1.1 on 2024-09-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_menu_items_image_alter_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
