# Generated by Django 5.1.1 on 2024-09-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_login_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
