# Generated by Django 5.1.1 on 2024-09-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_category_category_image_alter_login_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='image',
        ),
    ]
