# Generated by Django 5.1.1 on 2024-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_order_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_items',
            name='hide',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
