# Generated by Django 5.1.1 on 2024-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_menu_items_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='offer',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
