# Generated by Django 5.1.1 on 2024-09-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_menu_items_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='hide',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
