# Generated by Django 5.1.1 on 2024-09-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_menu_items_waiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_items',
            old_name='waiting',
            new_name='hide',
        ),
    ]
