# Generated by Django 5.1.1 on 2024-09-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_order_tablename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tablename',
            new_name='tablenumber',
        ),
    ]
