# Generated by Django 5.1.1 on 2024-09-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_tablename_order_tablenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_items',
            name='hide',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='menu_items',
            name='offer',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
