# Generated by Django 5.1.1 on 2024-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_name_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tablenumber',
            field=models.CharField(max_length=100),
        ),
    ]
